Foo 005 rw1
resource-watch/data-pre-processing pull request #223
Opened 2021-04-16 19:48 UTC by Edman25

## Checklist for Reviewing a Pre-Processing Script

- [ ] Does the python script contain the following 4 sections: Download data and save to your data directory, Process data, Upload processed data to Carto/Upload processed data to Google Earth Engine, Upload original data and processed data to Amazon S3 storage?
- [ ] Does the script have the standardized variable names for: dataset_name, raw_data_file, processed_data_file?
- [ ] Does the script create and use a 'data' directory?
- [ ] Does the script use a python module to automatically download the data? If this is not possible, are there explicit instructions for how to download the data (step by step with instructions about every input parameter and button to click to find the exact data) and does it use shutil to move the data from 'Downloads' into the data directory?
- [ ] Is the script automated as much as possible to minimize rewriting code the next time the dataset updates (ex 1: can you automatically pull out column names instead of typing them yourself? ex 2: if you are dropping columns with no data, did you use pandas to find the nodata columns instead of dropping the column by name?)
- [ ] Are there comments on almost every line of code to explicitly state what is being done and why?
- [ ] Are you uploading to the correct AWS location?
- [ ] For GEE scripts, did you explicitly define the band manifest with a pyramiding policy so that we can easily change it later if we need to?
- [ ] Does the README contain all relevant links?
- [ ] Does the README state the original file type?
- [ ] Does the README list all of the processing steps that were taken in the script?
- [ ] For netcdfs, does the README state which variables were pulled from the netcdf?
- [ ] Did you use the util functions whenever possible?
- [ ] Have you checked the processed data file on your computer to make sure it matches the data you uploaded to Carto? (spaces or symbol names in column titles often get changed in the upload process-please change these before uploading so that the backed up processed data matches the data on Carto)
- [ ] Does the folder name and python script file name match the dataset_name variable in the script? Are they all lowercase? Does the processing script end in '_processing.py'? (this part is often forgotten)

2021-06-08 18:56 UTC, amsnyder requested changes

2021-06-08 18:56 UTC, amsnyder commented on foo_005_rw1_crop_area_production/README.md
> +This file describes the data pre-processing that was done to [the Crop Land Area and Production](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/PRFF8V&version=4.0) for [disp
link to rw?

2021-06-08 18:56 UTC, amsnyder commented on foo_005_rw1_crop_area_production/README.md
> +You can view the processed Crop Land Area and Production dataset [on Resource Watch](in progress).
link to rw?

2021-06-08 18:56 UTC, amsnyder commented on foo_005_rw1_crop_area_production/README.md
> +###### Note: This dataset processing was done by [Eduardo Castillero Reyes](https://wrimexico.org/profile/eduardo-castillero-reyes), and QC'd by ....
```suggestion
###### Note: This dataset processing was done by [Eduardo Castillero Reyes](https://wrimexico.org/profile/eduardo-castillero-reyes), and QC'd by [Amelia Snyder](https://www.wri.org/profile/amelia-snyder).
```

2021-06-08 18:56 UTC, amsnyder commented on foo_005_rw1_crop_area_production/README.md
> +The data was provided by the source as two zip files containing multiple TIFF files. The files show the harvest and production areas for several crops and specific technologies. Only files encompassi
```suggestion
The data was provided by the source as two zip files containing multiple TIFF files. The files show the harvest and production areas for several crops, disaggregated by specific technologies. Only files encompassing maize, soybean, wheat, and rice crops were processed at the complete crop level were used (combining all technologies for a total).
```

2021-06-22 23:52 UTC, Edman25 commented on foo_005_rw1_crop_area_production/README.md
> +This file describes the data pre-processing that was done to [the Crop Land Area and Production](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/PRFF8V&version=4.0) for [disp
adding it

2021-06-22 23:53 UTC, Edman25 commented on foo_005_rw1_crop_area_production/README.md
> +You can view the processed Crop Land Area and Production dataset [on Resource Watch](in progress).
adding it

2022-02-09 23:06 UTC, merged