Wat.068
resource-watch/data-pre-processing pull request #235
Opened 2021-05-11 15:20 UTC by rachelthoms

## Checklist for Reviewing a Pre-Processing Script

- [ ] Does the python script contain the following 4 sections: Download data and save to your data directory, Process data, Upload processed data to Carto/Upload processed data to Google Earth Engine, Upload original data and processed data to Amazon S3 storage?
- [ ] Does the script have the standardized variable names for: dataset_name, raw_data_file, processed_data_file?
- [ ] Does the script create and use a 'data' directory?
- [ ] Does the script use a python module to automatically download the data? If this is not possible, are there explicit instructions for how to download the data (step by step with instructions about every input parameter and button to click to find the exact data) and does it use shutil to move the data from 'Downloads' into the data directory?
- [ ] Is the script automated as much as possible to minimize rewriting code the next time the dataset updates (ex 1: can you automatically pull out column names instead of typing them yourself? ex 2: if you are dropping columns with no data, did you use pandas to find the nodata columns instead of dropping the column by name?)
- [ ] Are there comments on almost every line of code to explicitly state what is being done and why?
- [ ] Are you uploading to the correct AWS location?
- [ ] For GEE scripts, did you explicitly define the band manifest with a pyramiding policy so that we can easily change it later if we need to?
- [ ] Does the README contain all relevant links?
- [ ] Does the README state the original file type?
- [ ] Does the README list all of the processing steps that were taken in the script?
- [ ] For netcdfs, does the README state which variables were pulled from the netcdf?
- [ ] Did you use the util functions whenever possible?
- [ ] Have you checked the processed data file on your computer to make sure it matches the data you uploaded to Carto? (spaces or symbol names in column titles often get changed in the upload process-please change these before uploading so that the backed up processed data matches the data on Carto)
- [ ] Does the folder name and python script file name match the dataset_name variable in the script? Are they all lowercase? Does the processing script end in '_processing.py'? (this part is often forgotten)

2021-05-18 20:46 UTC, adawyj97 requested changes

2021-05-19 18:57 UTC, rachelthoms commented on wat_068_rw0_watersheds/README.md
> +1. For each relevant basin level, read in the shapefiles for the nine regional tiles as a geopandas dataframe.
let me know if the recent push clarifies these points

2021-05-19 20:54 UTC, adawyj97 requested changes

2021-05-19 20:54 UTC, adawyj97 commented on wat_068_rw0_watersheds/README.md
> +Due to the resolution of the sub-basins delinations, the breakdowns provided by levels 3-8 are most relevant for analysis, and were thus selected for display on Resource Watch.
```suggestion
Due to the resolution of the sub-basins delineations, the breakdowns provided by levels 3-8 are most relevant for analysis, and were thus selected for display on Resource Watch. 
```

2021-05-19 20:54 UTC, adawyj97 commented on wat_068_rw0_watersheds/wat_068_rw0_watersheds_processing.py
> +
```suggestion
```

2021-05-19 20:54 UTC, adawyj97 commented on wat_068_rw0_watersheds/wat_068_rw0_watersheds_processing.py
> +        # create a str of the basin level padded by zeros, using the index
```suggestion
        # create a string of the basin level padded by zeros, using the index
```

2021-05-19 20:54 UTC, adawyj97 commented on wat_068_rw0_watersheds/wat_068_rw0_watersheds_processing.py
> +            # read shapefiles that include the corresponding basin level as a gdf
```suggestion
            # read shapefiles that include the corresponding basin level as a geopandas dataframe
```

2021-05-19 20:54 UTC, adawyj97 commented on wat_068_rw0_watersheds/wat_068_rw0_watersheds_processing.py
> +        # Create a list of the shapefile components by grabbing files that match the str
```suggestion
        # Create a list of the shapefile components by grabbing files that match the string
```

2021-05-19 20:54 UTC, adawyj97 commented on wat_068_rw0_watersheds/wat_068_rw0_watersheds_processing.py
> +        # merge gdfs for basin level
```suggestion
        # merge geopandas dataframes for basin level
```

2021-05-19 20:54 UTC, adawyj97 commented on wat_068_rw0_watersheds/wat_068_rw0_watersheds_processing.py
> +        # create an empty list to hold the gdfs to be merged (1 per region)
```suggestion
        # create an empty list to hold the geopandas dataframes to be merged (1 per region)
```

2021-05-19 20:54 UTC, adawyj97 commented on wat_068_rw0_watersheds/wat_068_rw0_watersheds_processing.py
> +            # read shapefiles that include the corresponding basin level as a gdf
```suggestion
            # read shapefiles that include the corresponding basin level as a geopandas dataframe
```

2021-05-19 20:54 UTC, adawyj97 commented on wat_068_rw0_watersheds/wat_068_rw0_watersheds_processing.py
> +                # Add the gdf to the list
```suggestion
                # Add the geopandas dataframe to the list
```

2021-05-19 20:54 UTC, adawyj97 commented on wat_068_rw0_watersheds/wat_068_rw0_watersheds_processing.py
> +
```suggestion
```

2021-05-19 20:54 UTC, adawyj97 commented on wat_068_rw0_watersheds/README.md
> +2. Combine shapefiles for each basin level into one shapefile that includes all regional tiles, with a column for 'level' to indicate which level the file represents.
```suggestion
2. Convert column names to lowercase to match Carto column name requirements.
3. Combine shapefiles for each basin level into one shapefile that includes all regional tiles, with a column for 'level' to indicate which level the file represents.
```

2021-05-20 15:20 UTC, adawyj97 requested changes

2021-05-20 15:20 UTC, adawyj97 commented on wat_068_rw0_watersheds/README.md
> +3. Upload the combined shapefile to Carto.
```suggestion
For each relevant basin level:
1. Read in the shapefiles for the nine regional tiles as a geopandas dataframe.
2. Convert the column names to lowercase to match Carto column name requirements.
3. Combine shapefiles for all regional tiles at the given level into one shapefile, with a column for 'level' to indicate which level the file represents.
4. Upload the combined shapefile to Carto.
```

2021-05-20 15:20 UTC, adawyj97 commented on wat_068_rw0_watersheds/wat_068_rw0_watersheds_processing.py
> +
```suggestion

```

2021-05-20 16:37 UTC, merged