Cli 017 rw1 glacier locations
resource-watch/data-pre-processing pull request #261
Opened 2021-08-03 18:52 UTC by jwinik

## Checklist for Reviewing a Pre-Processing Script

- [ ] Does the python script contain the following 4 sections: Download data and save to your data directory, Process data, Upload processed data to Carto/Upload processed data to Google Earth Engine, Upload original data and processed data to Amazon S3 storage?
- [ ] Does the script have the standardized variable names for: dataset_name, raw_data_file, processed_data_file?
- [ ] Does the script create and use a 'data' directory?
- [ ] Does the script use a python module to automatically download the data? If this is not possible, are there explicit instructions for how to download the data (step by step with instructions about every input parameter and button to click to find the exact data) and does it use shutil to move the data from 'Downloads' into the data directory?
- [ ] Is the script automated as much as possible to minimize rewriting code the next time the dataset updates (ex 1: can you automatically pull out column names instead of typing them yourself? ex 2: if you are dropping columns with no data, did you use pandas to find the nodata columns instead of dropping the column by name?)
- [ ] Are there comments on almost every line of code to explicitly state what is being done and why?
- [ ] Are you uploading to the correct AWS location?
- [ ] For GEE scripts, did you explicitly define the band manifest with a pyramiding policy so that we can easily change it later if we need to?
- [ ] Does the README contain all relevant links?
- [ ] Does the README state the original file type?
- [ ] Does the README list all of the processing steps that were taken in the script?
- [ ] For netcdfs, does the README state which variables were pulled from the netcdf?
- [ ] Did you use the util functions whenever possible?
- [ ] Have you checked the processed data file on your computer to make sure it matches the data you uploaded to Carto? (spaces or symbol names in column titles often get changed in the upload process-please change these before uploading so that the backed up processed data matches the data on Carto)
- [ ] Does the folder name and python script file name match the dataset_name variable in the script? Are they all lowercase? Does the processing script end in '_processing.py'? (this part is often forgotten)

2021-08-03 18:55 UTC, jwinik commented
I renamed the tables in Carto to be archived. 

Is the upload processed data to the Carto section formatted correctly? There are two Carto tables, so I assumed I had to repeat that line twice, but please let me know if I should format it differently.

2021-08-18 19:36 UTC, adawyj97 requested changes

2021-08-18 19:36 UTC, adawyj97 commented on cli_017_rw1_glacier_locations/cli_017_rw1_glacier_locations.py
> +    zip.write(processed_files, os.path.basename(processed_files))
```suggestion
# Copy the processed data into a zipped file to upload to S3
processed_data_dir = os.path.join(data_dir, dataset_name+'_edit.zip')
# find all the necessary components of the two shapefiles
processed_pt_files = glob.glob(os.path.join(data_dir, dataset_name + '_points_edit.*'))
processed_extent_files = glob.glob(os.path.join(data_dir, dataset_name +'_extent_edit.*'))
with ZipFile(processed_data_dir,'w') as zip:
    for file in processed_pt_files + processed_extent_files:
        zip.write(file, os.path.basename(file))
```

2021-08-18 19:36 UTC, adawyj97 commented on cli_017_rw1_glacier_locations/README.md
> +2. Rename columns to match Carto table and delete unnecessary columns.
```suggestion
2. Rename columns to match the current version of Carto table.
```

2026-07-14 12:52 UTC, hilljessica8787-dot approved these changes

2026-07-14 13:33 UTC, closed without merging